name: cellphy
channels:
  - defaults
  - talley
  - conda-forge
  - anaconda
dependencies:
  - cudatoolkit=9.0
  - appdirs=1.4.3
  - cffi=1.11.5
  - decorator=4.3.0
  - llvmlite=0.23.0
  - mako=1.0.7
  - markupsafe=1.0
  - ocl-icd=2.2.12
  - pandas=0.23.4
  - pycparser=2.18
  - python-dateutil=2.7.3
  - pytools=2018.5.2
  - pytz=2018.5
  - six=1.11.0
  - tifffile=0.15.1
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - automat=0.7.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=2.1.3
  - ca-certificates=2018.03.07
  - certifi=2018.8.13
  - cloudpickle=0.5.3
  - constantly=15.1.0
  - cryptography=2.3
  - cryptography-vectors=2.3
  - cudnn=7.1.2
  - cupy=4.1.0
  - cycler=0.10.0
  - dask-core=0.18.2
  - dbus=1.13.2
  - entrypoints=0.2.3
  - expat=2.2.5
  - fastrlock=0.3
  - fontconfig=2.12.6
  - freetype=2.8
  - future=0.16.0
  - glib=2.56.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.1
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - imageio=2.3.0
  - incremental=17.5.0
  - intel-openmp=2018.0.3
  - ipykernel=4.8.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - jsoncpp=1.8.3
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - libopenblas=0.2.20
  - libpng=1.6.34
  - libsodium=1.0.16
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libxcb=1.13
  - libxml2=2.9.8
  - matplotlib=2.2.2
  - mistune=0.8.3
  - mkl=2018.0.3
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nccl=1.3.5
  - ncurses=6.1
  - networkx=2.1
  - notebook=5.6.0
  - numba=0.38.1
  - numpy=1.13.3
  - numpy-base=1.14.3
  - olefile=0.45.1
  - openssl=1.0.2p
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.1.0
  - pip=10.0.1
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pyculib=1.0.2
  - pyculib_sorting=1.0.0
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=3.6.6
  - pywavelets=0.5.2
  - pyzmq=17.1.2
  - qt=5.9.5
  - readline=7.0
  - scikit-image=0.14.0
  - scipy=1.1.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.0.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - sqlite=3.24.0
  - tbb=2018.0.4
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - toolz=0.9.0
  - tornado=5.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - vtk=8.1.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - llspylibs=0.1.2
prefix: /home/cellphylab/anaconda3/envs/cellphy

